name: build

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: ['21', '25']
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Build ${{ matrix.java }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials:
          false    
    - name: Set up JDK
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
        cache: 'maven'
    - name: Build with Maven
      run: mvn --batch-mode verify